<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query as Query;

/**
 * MoviesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get movies from DB
     *
     * @param null $order order name from movies
     * @param null $dir order id from movies
     * @return array
     */
    public function listMoviesWithOrder($order = null, $dir = null)
    {

        $qb = $this
            ->createQueryBuilder("m");

        if ($order) {
            $qb->orderBy("m.name", $order);
        }

        if ($dir) {
            $qb->orderBy("m.id", $dir);
        }


        return $qb->getQuery()->getResult();
    }
}
