<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;


/**
 * MoviesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviesRepository extends EntityRepository
{

    const DEFAULT_ORDER = "asc";

    /**
     * Get movies from DB
     *
     * @param null $order by name from movies
     * @param null $dir order id from movies
     *
     * @return QueryBuilder
     */
    public function getMovies($order = null, $dir = null)
    {

        $qb = $this->createQueryBuilder("m");

        if ($dir == "") {
            $dir = self::DEFAULT_ORDER;
        }

        if ($order !== "") {
            $qb->orderBy("m." . $order, $dir);
        }

        return $qb;
    }

}
